### PR TITLE
Update assistance_links.py

### PR DESCRIPTION
**Pull request by maorninja**
Added fact that you can use all ARM9 entrypoints and not just A9LH for 7.0.5

Also added ReiNAND

### CODE REVIEW

**Comment by pokecraft98** [comment]
why reinand? we dont recommend any user to use it

**Comment by maorninja** [comment]
Well, its still a CFW non otherless.

**Comment by pokecraft98** [comment]
Still no point of it being in the cog. I dont think we would like to support a shitty dev. luma3ds does everything reinand does and more and better.

**Comment by maorninja** [comment]
"and more" That's exactly why people like to use ReiNAND. They don't need all the new stuff that luma added.

**Comment by PhazonicRidley** [comment]
i would add it, but no one really uses reinand. Luma is the reccomended cfw to use it just does more and works very well thanks for the pr but i dont think reinand is going to be used thats all

**Comment by GriffinG1** [comment]
Yeah let's not touch ReiNAND

**Pull request closed without merging**
